# Apache Derby connection settings
# Choose ONE of the following URL styles:

# (A) Embedded (creates/uses local folder ./data/appdb)
#db.url=jdbc:derby:./data/appdb;create=true 
db.url=jdbc:derby://localhost:1527/C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\EnsariumPOS\\data\\ensariumDB;create=true
#db.url=jdbc:derby://localhost:1527/ensariumDB;
# (B) Network client (connect to a Derby Network Server)
# db.url=jdbc:derby://localhost:1527/appdb;create=true

# Credentials: Derby embedded usually ignores username/password; Network Server can enforce auth if enabled.
db.user=
db.password=
