/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.aldrin.ensarium.txn;

import com.aldrin.ensarium.icons.FaSwingIcons;
import com.aldrin.ensarium.security.Session;
import com.aldrin.ensarium.ui.widgets.BootstrapTableStyle;
import com.aldrin.ensarium.ui.widgets.RoundedPanel;
import com.aldrin.ensarium.ui.widgets.RoundedScrollPane;
import de.jensd.fx.glyphs.fontawesome.FontAwesomeIcon;
import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Window;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.Timer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author ALDRIN CABUSOG
 */
public class TxnPanel extends javax.swing.JPanel {


    private final InventoryTxnDao dao = new InventoryTxnDao();
    private final InventoryTxnTableModel tableModel = new InventoryTxnTableModel();
    private final JTable table = new JTable(tableModel);
    private final Session session;
    private final JPopupMenu popupMenu = new JPopupMenu();


    private int hoveredRow = -1;

    private final Icon iconSearch = FaSwingIcons.icon(FontAwesomeIcon.SEARCH, 20, Color.BLACK);
    private final Icon iconRefresh = FaSwingIcons.icon(FontAwesomeIcon.REFRESH, 20, Color.BLACK);

    public TxnPanel(Session session) {
        initComponents();
        this.session = session;


        roundedPanel1.add(buildCenterPanel(), BorderLayout.CENTER);

        jSpinner1.setModel(new SpinnerNumberModel(100, 1, 10000, 1));
        jSpinner1.setValue(100);
        buildPopupMenu();

        searchField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                loadTransactions();
            }
        });
        searchField.putClientProperty("JTextField.placeholderText", "Search reference, type, note, or creator");
        jSpinner1.addChangeListener(e -> loadTransactions());

        table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        BootstrapTableStyle.install(table);
        hideColumn(0);
        hideColumn(1);
        BootstrapTableStyle.setFixedColumnWidth(table, 1, 70);
        BootstrapTableStyle.setColumnWidth(table, 2, 150);
        BootstrapTableStyle.setColumnWidth(table, 3, 260);
        BootstrapTableStyle.setColumnWidth(table, 4, 80);
        BootstrapTableStyle.setColumnWidth(table, 5, 90);
        BootstrapTableStyle.setColumnWidth(table, 6, 120);
        BootstrapTableStyle.setColumnWidth(table, 7, 160);
        BootstrapTableStyle.setColumnWidth(table, 8, 160);
        BootstrapTableStyle.setColumnWidth(table, 9, 280);

        BootstrapTableStyle.setColumnRight(table, 1);
        BootstrapTableStyle.setHeaderRight(table, 1);
        for (int i = 2; i < table.getColumnCount(); i++) {
            BootstrapTableStyle.setColumnLeft(table, i);
            BootstrapTableStyle.setHeaderLeft(table, i);
        }

        installTableHover();
        loadTransactions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField(30);
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        roundedPanel1 = new com.aldrin.ensarium.ui.widgets.RoundedPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(1116, 50));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setText("Search:");
        jPanel3.add(jLabel1);

        searchField.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel3.add(searchField);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText("Rows:");
        jPanel3.add(jLabel2);

        jSpinner1.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.add(jSpinner1);

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setPreferredSize(new java.awt.Dimension(1116, 35));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));
        jPanel4.add(statusLabel);

        jPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jPanel5.setPreferredSize(new java.awt.Dimension(10, 534));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.EAST);

        jPanel6.setPreferredSize(new java.awt.Dimension(10, 534));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.LINE_START);

        roundedPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(roundedPanel1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSpinner jSpinner1;
    private com.aldrin.ensarium.ui.widgets.RoundedPanel roundedPanel1;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
    private RoundedScrollPane buildCenterPanel() {
        table.setComponentPopupMenu(popupMenu);

        table.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                selectRowOnPopup(e);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                selectRowOnPopup(e);
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2 && table.getSelectedRow() >= 0) {
                    viewSelectedTransactionDetails();
                }
            }
        });

        RoundedScrollPane scrollPane = new RoundedScrollPane(table);
//        scrollPane.setBorder(BorderFactory.createTitledBorder("Inventory Transactions"));
        return scrollPane;
    }

    private JPanel buildBottomPanel() {
        JPanel panel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        panel.add(statusLabel);
        return panel;
    }

    private void buildPopupMenu() {
        JMenuItem miViewDetails = new JMenuItem("View Details");
        JMenuItem miRefresh = new JMenuItem("Refresh");
        miViewDetails.setIcon(iconSearch);
        miRefresh.setIcon(iconRefresh);

        miViewDetails.addActionListener(e -> viewSelectedTransactionDetails());
        miRefresh.addActionListener(e -> loadTransactions());

        popupMenu.add(miViewDetails);
        popupMenu.addSeparator();
        popupMenu.add(miRefresh);
    }

    private void selectRowOnPopup(MouseEvent e) {
        if (e.isPopupTrigger()) {
            int row = table.rowAtPoint(e.getPoint());
            if (row >= 0) {
                table.setRowSelectionInterval(row, row);
            }
        }
    }

    private void loadTransactions() {
        String keyword = searchField.getText();
        int limit = (Integer) jSpinner1.getValue();
        statusLabel.setText("Loading...");

        new SwingWorker<List<InventoryTxn>, Void>() {
            @Override
            protected List<InventoryTxn> doInBackground() throws Exception {
                return dao.findTransactions(keyword, limit);
            }

            @Override
            protected void done() {
                try {
                    List<InventoryTxn> rows = get();
                    tableModel.setRows(rows);
                    statusLabel.setText(rows.size() + " row(s) loaded.");
                } catch (Exception ex) {
                    statusLabel.setText("Load failed.");
                    SwingUtils.showError(TxnPanel.this, "Failed to load inventory transactions.", ex instanceof Exception ? (Exception) ex : null);
                }
            }
        }.execute();
    }

    private void viewSelectedTransactionDetails() {
        int selectedRow = table.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a transaction first.", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        InventoryTxn txn = tableModel.getRow(selectedRow);
        if (txn == null) {
            return;
        }

        Window owner = SwingUtilities.getWindowAncestor(this);
        DonutLoadingDialog loadingDialog = new DonutLoadingDialog(owner, "Loading transaction details...");
        InventoryTxnDetailsDialog dialog = new InventoryTxnDetailsDialog(owner);

        new SwingWorker<Void, Void>() {
            private Exception error;

            @Override
            protected Void doInBackground() {
                try {
                    dialog.loadTransaction(txn.getId());
                } catch (Exception ex) {
                    error = ex;
                }
                return null;
            }

            @Override
            protected void done() {
                loadingDialog.dispose();
                if (error != null) {
                    if (error instanceof SQLException sqlEx) {
                        SwingUtils.showError(TxnPanel.this, "Failed to load transaction details.", sqlEx);
                    } else {
                        SwingUtils.showError(TxnPanel.this, "Failed to load transaction details.", error instanceof Exception ? error : new Exception(error));
                    }
                    return;
                }
                dialog.setVisible(true);
            }
        }.execute();

        loadingDialog.setVisible(true);
    }

    private void hideColumn(int i) {
        table.getColumnModel().getColumn(i).setMinWidth(0);
        table.getColumnModel().getColumn(i).setMaxWidth(0);
        table.getColumnModel().getColumn(i).setPreferredWidth(0);
        table.getColumnModel().getColumn(i).setResizable(false);
    }

    private void installTableHover() {
        table.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseMoved(java.awt.event.MouseEvent e) {
                int row = table.rowAtPoint(e.getPoint());
                if (row != hoveredRow) {
                    hoveredRow = row;
                    table.repaint();
                }
            }
        });

        table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                if (hoveredRow != -1) {
                    hoveredRow = -1;
                    table.repaint();
                }
            }
        });
    }

    static class DonutLoadingDialog extends JDialog {

        private final DonutSpinner spinner;

        public DonutLoadingDialog(Window owner, String message) {
            super(owner, "Loading", Dialog.ModalityType.MODELESS);
            setUndecorated(true);
            JPanel panel = new JPanel(new BorderLayout(10, 10));
            panel.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(new Color(0xD0D7DE)),
                    BorderFactory.createEmptyBorder(16, 16, 16, 16)
            ));
            panel.setBackground(Color.WHITE);
            spinner = new DonutSpinner();
            JLabel lblMessage = new JLabel(message, SwingConstants.CENTER);
            lblMessage.setForeground(new Color(60, 60, 60));
            panel.add(spinner, BorderLayout.CENTER);
            panel.add(lblMessage, BorderLayout.SOUTH);
            setContentPane(panel);
            setSize(220, 180);
            setLocationRelativeTo(owner);
            spinner.start();
        }

        @Override
        public void dispose() {
            spinner.stop();
            super.dispose();
        }
    }

    static class DonutSpinner extends JPanel {

        private int angle = 0;
        private final Timer timer;

        public DonutSpinner() {
            setOpaque(false);
            setPreferredSize(new Dimension(90, 90));
            timer = new Timer(20, e -> {
                angle += 8;
                if (angle >= 360) {
                    angle = 0;
                }
                repaint();
            });
        }

        public void start() {
            if (!timer.isRunning()) {
                timer.start();
            }
        }

        public void stop() {
            if (timer.isRunning()) {
                timer.stop();
            }
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            int size = Math.min(getWidth(), getHeight()) - 14;
            int x = (getWidth() - size) / 2;
            int y = (getHeight() - size) / 2;
            g2.setStroke(new BasicStroke(10f, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND));
            g2.setColor(new Color(230, 235, 240));
            g2.drawArc(x, y, size, size, 0, 360);
            g2.setColor(new Color(0, 120, 215));
            g2.drawArc(x, y, size, size, angle, 110);
            g2.dispose();
        }
    }
}
