/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.ensarium.dispense;

import com.aldrin.ensarium.db.Db;
import com.aldrin.ensarium.icons.FaSwingIcons;
import com.aldrin.ensarium.icons.Icons;
import com.aldrin.ensarium.util.ComboBoxAutoFill;
import de.jensd.fx.glyphs.fontawesome.FontAwesomeIcon;
import java.awt.Color;
import java.awt.Dialog;
import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

/**
 *
 * @author ALDRIN CABUSOG
 */
public class DiscountDialog2 extends javax.swing.JDialog {

    private static final String MANUAL = "<Manual Discount>";

    private final DiscountTypeDao discountTypeDao = new DiscountTypeDao();
    private final JLabel lblHint = new JLabel("Choose any active discount type or enter a manual discount.");
    private SaleDiscountInfo result;
    private final List<DiscountTypeRef> loadedTypes = new ArrayList<>();

    Icon iconOk = FaSwingIcons.icon(FontAwesomeIcon.MOUSE_POINTER, 24, Color.WHITE);
    Icon iconClear = FaSwingIcons.icon(FontAwesomeIcon.TRASH_ALT, 24, Color.WHITE);
    Icon iconCancel = FaSwingIcons.icon(FontAwesomeIcon.CLOSE, 24, Color.WHITE);
    Icon iconWalkIn = Icons.walking(24, Color.WHITE);

    public DiscountDialog2(java.awt.Window owner, DispenseService service) {
        super(owner, "Discount", Dialog.ModalityType.APPLICATION_MODAL);

        initComponents();
        rbAmount.setSelected(true);

        btnOk.addActionListener(e -> apply());
        btnClear.addActionListener(e -> {
            result = null;
            dispose();
        });
        btnCancel.addActionListener(e -> dispose());

        btnOk.setPrimary();
        btnCancel.setDanger();
        btnClear.setDanger();
        
        btnOk.setIcon(iconOk);
        btnClear.setIcon(iconClear);
        btnCancel.setIcon(iconCancel);
        
        cmbDiscountType.addActionListener(e -> syncSelectedType());

        txtName.setEditable(true);
        loadDiscountTypes();
        
        applyComboBoxAutoFill(cmbDiscountType);


        setSize(560, 250);
        setLocationRelativeTo(owner);
    }
    
                 private static void applyComboBoxAutoFill(JComboBox<?> combo) {
        combo.setEditable(true);
        JTextComponent editor = (JTextComponent) combo.getEditor().getEditorComponent();
        editor.setDocument(new ComboBoxAutoFill(combo));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        cmbDiscountType = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        txtValue = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        rbPercent = new javax.swing.JRadioButton();
        rbAmount = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        btnOk = new com.aldrin.ensarium.ui.widgets.StyledButton();
        btnClear = new com.aldrin.ensarium.ui.widgets.StyledButton();
        btnCancel = new com.aldrin.ensarium.ui.widgets.StyledButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.GridLayout(0, 1, 0, 5));
        jPanel8.add(cmbDiscountType);

        txtName.setText("Manual Discount");
        jPanel8.add(txtName);

        txtValue.setText("0");
        jPanel8.add(txtValue);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(rbPercent);
        rbPercent.setText("Percent (example: 0.10)");
        jPanel10.add(rbPercent);

        buttonGroup1.add(rbAmount);
        rbAmount.setText("Amount");
        jPanel10.add(rbAmount);

        jPanel8.add(jPanel10);

        jPanel5.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel9.setPreferredSize(new java.awt.Dimension(100, 221));
        jPanel9.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setText("Discount type");
        jPanel9.add(jLabel1);

        jLabel2.setText("Name");
        jPanel9.add(jLabel2);

        jLabel3.setText("Value");
        jPanel9.add(jLabel3);

        jLabel4.setText("Kind");
        jPanel9.add(jLabel4);

        jPanel5.add(jPanel9, java.awt.BorderLayout.WEST);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(10, 100));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.WEST);

        jPanel7.setPreferredSize(new java.awt.Dimension(10, 221));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(662, 10));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.GridLayout(0, 1));

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel5.setText("Choose any active discount type or enter a manual discount ");
        jPanel11.add(jLabel5);

        jPanel4.add(jPanel11);

        btnOk.setText("Apply");
        jPanel12.add(btnOk);

        btnClear.setText("Clear");
        jPanel12.add(btnClear);

        btnCancel.setText("Cancel");
        jPanel12.add(btnCancel);

        jPanel4.add(jPanel12);

        jPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.aldrin.ensarium.ui.widgets.StyledButton btnCancel;
    private com.aldrin.ensarium.ui.widgets.StyledButton btnClear;
    private com.aldrin.ensarium.ui.widgets.StyledButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Object> cmbDiscountType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton rbAmount;
    private javax.swing.JRadioButton rbPercent;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables

    private void loadDiscountTypes() {
        SearchableComboBoxSupport.beginBulkUpdate(cmbDiscountType);
        try {
            cmbDiscountType.removeAllItems();
            loadedTypes.clear();
            cmbDiscountType.addItem(MANUAL);
            try (Connection conn = Db.getConnection()) {
                conn.setAutoCommit(false);
                loadedTypes.addAll(discountTypeDao.listActive(conn));
                conn.commit();
                for (DiscountTypeRef type : loadedTypes) {
                    cmbDiscountType.addItem(type);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Could not load discount types: " + ex.getMessage(), "Discount", JOptionPane.WARNING_MESSAGE);
            }
            if (cmbDiscountType.getItemCount() > 0) {
                cmbDiscountType.setSelectedIndex(0);
            }
            syncSelectedType();
        } finally {
            SearchableComboBoxSupport.endBulkUpdate(cmbDiscountType);
        }
    }

    private void syncSelectedType() {
        Object selected = cmbDiscountType.getSelectedItem();
        if (!(selected instanceof DiscountTypeRef type)) {
            restoreManualMode();
            return;
        }
        txtName.setText(type.name == null ? "Discount" : type.name);
        txtName.setEditable(false);
        if (type.isPercent()) {
            rbPercent.setSelected(true);
        } else {
            rbAmount.setSelected(true);
        }
        rbPercent.setEnabled(false);
        rbAmount.setEnabled(false);
        lblHint.setText("Code: " + safe(type.code) + " | Applies To: " + safe(type.appliesTo));
    }

    private void restoreManualMode() {
        Object selected = cmbDiscountType.getSelectedItem();
        boolean manual = !(selected instanceof DiscountTypeRef);
        txtName.setEditable(manual);
        rbPercent.setEnabled(manual);
        rbAmount.setEnabled(manual);
        if (manual) {
            lblHint.setText("Choose any active discount type or enter a manual discount.");
        }
    }

    private void apply() {
        try {
            SaleDiscountInfo di = new SaleDiscountInfo();
            Object selected = cmbDiscountType.getSelectedItem();
            if (selected instanceof DiscountTypeRef type) {
                di.discountTypeId = type.id;
                di.discountCode = type.code;
                di.appliesTo = type.appliesTo;
                di.name = type.name == null || type.name.isBlank() ? "Discount" : type.name;
                di.kind = type.kind;
            } else {
                di.name = txtName.getText().trim().isBlank() ? "Manual Discount" : txtName.getText().trim();
                di.kind = rbPercent.isSelected() ? SaleDiscountInfo.KIND_PERCENT : SaleDiscountInfo.KIND_AMOUNT;
            }
            di.value = new BigDecimal(txtValue.getText().trim());
            if (di.value.compareTo(BigDecimal.ZERO) < 0) {
                throw new IllegalArgumentException("Discount must not be negative.");
            }
            result = di;
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Invalid discount value.");
        }
    }

    public SaleDiscountInfo showDialog(SaleDiscountInfo current) {
        loadDiscountTypes();
        if (current != null) {
            txtName.setText(current.name == null ? "Manual Discount" : current.name);
            txtValue.setText(current.value == null ? "0" : current.value.toPlainString());
            if (current.isPercent()) {
                rbPercent.setSelected(true);
            } else {
                rbAmount.setSelected(true);
            }
            boolean matched = false;
            if (current.discountTypeId != null) {
                for (int i = 0; i < cmbDiscountType.getItemCount(); i++) {
                    Object item = cmbDiscountType.getItemAt(i);
                    if (item instanceof DiscountTypeRef type && current.discountTypeId.equals(type.id)) {
                        cmbDiscountType.setSelectedIndex(i);
                        matched = true;
                        break;
                    }
                }
            }
            if (!matched) {
                cmbDiscountType.setSelectedIndex(0);
            }
        } else {
            txtName.setText("Manual Discount");
            txtValue.setText("0");
            rbAmount.setSelected(true);
            cmbDiscountType.setSelectedIndex(0);
        }
        restoreManualMode();
        setVisible(true);
        return result;
    }

    private String safe(String s) {
        return s == null ? "" : s;
    }
}
