/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.ensarium.dispense;

import com.aldrin.ensarium.icons.FaSwingIcons;
import com.aldrin.ensarium.ui.widgets.RoundedScrollPane;
import de.jensd.fx.glyphs.fontawesome.FontAwesomeIcon;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Dimension;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author ALDRIN CABUSOG
 */
public class HoldDialog2 extends javax.swing.JDialog {
    
    private final DispenseService service;
    private final HoldDialog2.HoldTableModel model = new HoldDialog2.HoldTableModel();
    private final JTable table = new JTable(model);
    private Long result;
    
    Icon iconLoad = FaSwingIcons.icon(FontAwesomeIcon.DOWNLOAD, 24, Color.WHITE);
    Icon iconCancel = FaSwingIcons.icon(FontAwesomeIcon.CLOSE, 24, Color.WHITE);
    
    public HoldDialog2(java.awt.Window owner, DispenseService service) throws Exception {
        super(owner, "Held Tickets", Dialog.ModalityType.APPLICATION_MODAL);
        initComponents();
        this.service = service;
        table.setAutoCreateRowSorter(true);
        panelTable.add(new RoundedScrollPane(table), BorderLayout.CENTER);
        JPanel bottom = new JPanel();
        
        btnLoad.setIcon(iconLoad);
        btnCancel.setIcon(iconCancel);
        
        btnCancel.setDanger();
        
        add(bottom, BorderLayout.SOUTH);
        btnLoad.addActionListener(e -> choose());
        btnCancel.addActionListener(e -> dispose());
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {
                    choose();
                }
            }
        });
        model.setRows(service.listHolds());
        
        table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        DefaultTableCellRenderer left = new DefaultTableCellRenderer();
        left.setHorizontalAlignment(SwingConstants.LEFT);
        DefaultTableCellRenderer right = new DefaultTableCellRenderer();
        right.setHorizontalAlignment(SwingConstants.RIGHT);

//        table.setShowGrid(false);
        table.setIntercellSpacing(new Dimension(0, 0));
        table.setSelectionBackground(new Color(0xD6E9FF));
        table.setSelectionForeground(Color.BLACK);
        
        table.getColumnModel().getColumn(0).setCellRenderer(left);
        table.getColumnModel().getColumn(1).setCellRenderer(left);
        table.getColumnModel().getColumn(2).setCellRenderer(left);
        table.getColumnModel().getColumn(3).setCellRenderer(left);
        
        table.getTableHeader().setBorder(
                BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(0xD0D7DE))
        );
        
        final TableCellRenderer hdrRenderer = table.getTableHeader().getDefaultRenderer();
        table.getTableHeader().setDefaultRenderer((tbl, value, isSelected, hasFocus, row, col) -> {
            Component c = hdrRenderer.getTableCellRendererComponent(tbl, value, isSelected, hasFocus, row, col);
            
            if (c instanceof JLabel l) {
                l.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(0xD0D7DE)));
                if (col == 0) {
                    l.setHorizontalAlignment(SwingConstants.LEFT);
                } else if (col == 1) {
                    l.setHorizontalAlignment(SwingConstants.LEFT);
                } else if (col == 2) {
                    l.setHorizontalAlignment(SwingConstants.LEFT);
                } else if (col == 3) {
                    l.setHorizontalAlignment(SwingConstants.LEFT);
                }                
            }
            return c;
        });
        
        table.getColumnModel().getColumn(0).setPreferredWidth(120);
        table.getColumnModel().getColumn(1).setPreferredWidth(200);
        table.getColumnModel().getColumn(2).setPreferredWidth(150);
        table.getColumnModel().getColumn(3).setPreferredWidth(120);
        hideColumn(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelTable = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnLoad = new com.aldrin.ensarium.ui.widgets.StyledButton();
        btnCancel = new com.aldrin.ensarium.ui.widgets.StyledButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        panelTable.setLayout(new java.awt.BorderLayout());
        jPanel1.add(panelTable, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(678, 10));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setPreferredSize(new java.awt.Dimension(678, 50));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        btnLoad.setText("Load");
        jPanel4.add(btnLoad);

        btnCancel.setText("Cancel");
        jPanel4.add(btnCancel);

        jPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel5.setPreferredSize(new java.awt.Dimension(10, 298));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel6.setPreferredSize(new java.awt.Dimension(10, 298));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, java.awt.BorderLayout.EAST);

        setSize(new java.awt.Dimension(694, 307));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.aldrin.ensarium.ui.widgets.StyledButton btnCancel;
    private com.aldrin.ensarium.ui.widgets.StyledButton btnLoad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel panelTable;
    // End of variables declaration//GEN-END:variables
    private void choose() {
        int row = table.getSelectedRow();
        if (row < 0) {
            return;
        }
        int modelRow = table.convertRowIndexToModel(row);
        result = model.get(modelRow).id;
        dispose();
    }
    
    public Long showDialog() {
        setVisible(true);
        return result;
    }
    
    private static class HoldTableModel extends AbstractTableModel {
        
        private final String[] cols = {"ID", "Held At", "Customer", "Items"};
        private List<HeldSale> rows = new ArrayList<>();
        
        public void setRows(List<HeldSale> rows) {
            this.rows = rows;
            fireTableDataChanged();
        }
        
        public HeldSale get(int i) {
            return rows.get(i);
        }
        
        @Override
        public int getRowCount() {
            return rows.size();
        }
        
        @Override
        public int getColumnCount() {
            return cols.length;
        }
        
        @Override
        public String getColumnName(int c) {
            return cols[c];
        }
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MMM-dd hh:mm:ss a");
        @Override
        public Object getValueAt(int r, int c) {
            HeldSale h = rows.get(r);
            return switch (c) {
                case 0 ->
                    h.id;
                case 1 ->
                    h.heldAt.format(formatter);
                case 2 ->
                    h.customerName == null ? "Walk-in" : h.customerName;
                default ->
                    h.lines.size();
            };
        }
    }
    
    private void hideColumn(int i) {
        table.getColumnModel().getColumn(i).setMinWidth(0);
        table.getColumnModel().getColumn(i).setMaxWidth(0);
        table.getColumnModel().getColumn(i).setPreferredWidth(0);
        table.getColumnModel().getColumn(i).setResizable(false);
    }
}
