/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.ensarium.dispense;

import com.aldrin.ensarium.ui.widgets.BootstrapTableStyle;
import com.aldrin.ensarium.ui.widgets.RoundedScrollPane;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Dimension;
import java.text.DecimalFormat;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author ALDRIN CABUSOG
 */
public class SaleDetailDialog2 extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SaleDetailDialog2.class.getName());

    private final SaleDetailDialog2.LineTableModel model = new SaleDetailDialog2.LineTableModel();


    public SaleDetailDialog2(java.awt.Window owner, SaleDetailView detail) {
        super(owner, "Dispense Details", Dialog.ModalityType.APPLICATION_MODAL);
        initComponents();

        lblSaleNo.setText("-");
        lblDate.setText("-");
        lblCustomer.setText("-");
        lblCashier.setText("-");
        lblInvoice.setText("-");
        lblItems.setText("0");
        lblTotal.setText("0.00");

//        JTable table = new JTable(model);
        panelTable.add(new RoundedScrollPane(table), BorderLayout.CENTER);

        lblNotes.setEditable(false);
        lblNotes.setLineWrap(true);
        lblNotes.setWrapStyleWord(true);

        table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);


        BootstrapTableStyle.installAll(this);

        table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        BootstrapTableStyle.setFixedColumnWidth(table, 0, 70);
        BootstrapTableStyle.setColumnWidth(table, 1, 300);
        BootstrapTableStyle.setColumnWidth(table, 2, 150);
        BootstrapTableStyle.setColumnWidth(table, 3, 150);
        BootstrapTableStyle.setColumnWidth(table, 4, 100);
        BootstrapTableStyle.setColumnWidth(table, 5, 100);
        BootstrapTableStyle.setColumnWidth(table, 6, 100);

        BootstrapTableStyle.setColumnRight(table, 0);
        BootstrapTableStyle.setColumnLeft(table, 1);
        BootstrapTableStyle.setColumnLeft(table, 2);
        BootstrapTableStyle.setColumnLeft(table, 3);
        BootstrapTableStyle.setColumnRight(table, 4);
        BootstrapTableStyle.setColumnRight(table, 5);
        BootstrapTableStyle.setColumnRight(table, 6);

        BootstrapTableStyle.setHeaderRight(table, 0);
        BootstrapTableStyle.setHeaderLeft(table, 1);
        BootstrapTableStyle.setHeaderLeft(table, 2);
        BootstrapTableStyle.setHeaderLeft(table, 3);
        BootstrapTableStyle.setHeaderRight(table, 4);
        BootstrapTableStyle.setHeaderRight(table, 5);
        BootstrapTableStyle.setHeaderRight(table, 6);

        installTableHover();

        bind(detail);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelTable = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lblSaleNo = new javax.swing.JTextField();
        lblCustomer = new javax.swing.JTextField();
        lblInvoice = new javax.swing.JTextField();
        lblTotal = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        lblDate = new javax.swing.JTextField();
        lblCashier = new javax.swing.JTextField();
        lblItems = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lblNotes = new javax.swing.JTextArea(3, 20);
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        panelTable.setLayout(new java.awt.BorderLayout());
        jPanel2.add(panelTable, java.awt.BorderLayout.CENTER);

        jPanel14.setPreferredSize(new java.awt.Dimension(875, 10));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel14, java.awt.BorderLayout.NORTH);

        jPanel23.setPreferredSize(new java.awt.Dimension(10, 249));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel23, java.awt.BorderLayout.WEST);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(0, 110));
        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jPanel9.setPreferredSize(new java.awt.Dimension(437, 80));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel11.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        lblSaleNo.setEditable(false);
        lblSaleNo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblSaleNo.setFocusable(false);
        jPanel11.add(lblSaleNo);

        lblCustomer.setEditable(false);
        lblCustomer.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblCustomer.setFocusable(false);
        jPanel11.add(lblCustomer);

        lblInvoice.setEditable(false);
        lblInvoice.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblInvoice.setFocusable(false);
        jPanel11.add(lblInvoice);

        lblTotal.setEditable(false);
        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblTotal.setFocusable(false);
        jPanel11.add(lblTotal);

        jPanel15.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel12.setPreferredSize(new java.awt.Dimension(90, 80));
        jPanel12.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setText("Sale No");
        jPanel12.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText("Customer");
        jPanel12.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Invoice");
        jPanel12.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("Total");
        jPanel12.add(jLabel4);

        jPanel15.add(jPanel12, java.awt.BorderLayout.WEST);

        jPanel9.add(jPanel15, java.awt.BorderLayout.CENTER);

        jPanel16.setPreferredSize(new java.awt.Dimension(10, 110));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel16, java.awt.BorderLayout.WEST);

        jPanel3.add(jPanel9);

        jPanel17.setPreferredSize(new java.awt.Dimension(437, 80));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel19.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        lblDate.setEditable(false);
        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblDate.setFocusable(false);
        jPanel19.add(lblDate);

        lblCashier.setEditable(false);
        lblCashier.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblCashier.setFocusable(false);
        jPanel19.add(lblCashier);

        lblItems.setEditable(false);
        lblItems.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblItems.setFocusable(false);
        jPanel19.add(lblItems);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel19.add(jPanel22);

        jPanel18.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel20.setPreferredSize(new java.awt.Dimension(90, 80));
        jPanel20.setLayout(new java.awt.GridLayout(0, 1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("Date");
        jPanel20.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("Cashier");
        jPanel20.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("Items");
        jPanel20.add(jLabel7);
        jPanel20.add(jLabel8);

        jPanel18.add(jPanel20, java.awt.BorderLayout.WEST);

        jPanel17.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel21.setPreferredSize(new java.awt.Dimension(10, 110));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel21, java.awt.BorderLayout.WEST);

        jPanel3.add(jPanel17);

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel8.setPreferredSize(new java.awt.Dimension(875, 50));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel10.setPreferredSize(new java.awt.Dimension(10, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel10, java.awt.BorderLayout.WEST);

        lblNotes.setEditable(false);
        lblNotes.setColumns(20);
        lblNotes.setRows(5);
        lblNotes.setText("Notes\n");
        jPanel8.add(lblNotes, java.awt.BorderLayout.CENTER);

        jPanel4.setPreferredSize(new java.awt.Dimension(885, 10));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel8, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel5.setPreferredSize(new java.awt.Dimension(10, 388));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1046, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel7.setPreferredSize(new java.awt.Dimension(895, 20));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1046, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(1062, 505));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField lblCashier;
    private javax.swing.JTextField lblCustomer;
    private javax.swing.JTextField lblDate;
    private javax.swing.JTextField lblInvoice;
    private javax.swing.JTextField lblItems;
    private javax.swing.JTextArea lblNotes;
    private javax.swing.JTextField lblSaleNo;
    private javax.swing.JTextField lblTotal;
    private javax.swing.JPanel panelTable;
    // End of variables declaration//GEN-END:variables

    private void bind(SaleDetailView d) {
        DecimalFormat money = new DecimalFormat("#,##0.00");
        lblSaleNo.setText(d.saleNo == null ? "-" : d.saleNo);
        lblDate.setText(d.soldAt == null ? "-" : d.soldAt.toString());
        lblCustomer.setText(d.customerName == null || d.customerName.isBlank() ? "Walk-in" : d.customerName);
        lblCashier.setText(d.cashierUsername == null || d.cashierUsername.isBlank() ? "-" : d.cashierUsername);
        lblInvoice.setText(d.invoiceNo == null || d.invoiceNo.isBlank() ? "-" : d.invoiceNo);
        lblItems.setText(String.valueOf(d.itemCount));
        lblTotal.setText(money.format(d.total));
        lblNotes.setText(d.notes == null ? "" : d.notes);
        model.setLines(d.lines);
    }

    private static class LineTableModel extends AbstractTableModel {

        private final String[] cols = {"#", "Product", "SKU", "Barcode", "Qty", "Unit Price", "Line Total"};
        private java.util.List<SaleDetailLine> lines = new java.util.ArrayList<>();
        private final DecimalFormat money = new DecimalFormat("#,##0.00");

        public void setLines(java.util.List<SaleDetailLine> lines) {
            this.lines = lines;
            fireTableDataChanged();
        }

        @Override
        public int getRowCount() {
            return lines.size();
        }

        @Override
        public int getColumnCount() {
            return cols.length;
        }

        @Override
        public String getColumnName(int c) {
            return cols[c];
        }

        @Override
        public Object getValueAt(int r, int c) {
            SaleDetailLine x = lines.get(r);
            return switch (c) {
                case 0 ->
                    x.lineNo;
                case 1 ->
                    x.productName;
                case 2 ->
                    x.sku;
                case 3 ->
                    x.barcode;
                case 4 ->
                    money.format(x.qty);
                case 5 ->
                    money.format(x.unitPrice);
                default ->
                    money.format(x.lineTotal);
            };
        }
    }

    private int hoveredRow = -1;
    private final JTable table = new JTable(model) {
        @Override
        public Component prepareRenderer(TableCellRenderer renderer, int row, int column) {
            Component c = super.prepareRenderer(renderer, row, column);

            if (!isRowSelected(row)) {
                if (row == hoveredRow) {
                    c.setBackground(new Color(0xE8F2FF)); // hover color
                } else {
                    c.setBackground((row % 2 == 0) ? Color.WHITE : new Color(0xF7F9FC)); // stripes
                }
                c.setForeground(Color.BLACK);
            } else {
                c.setBackground(getSelectionBackground());
                c.setForeground(getSelectionForeground());
            }

            if (c instanceof JComponent jc) {
                jc.setOpaque(true);
            }

            return c;
        }
    };

    private void installTableHover() {
        table.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseMoved(java.awt.event.MouseEvent e) {
                int row = table.rowAtPoint(e.getPoint());
                if (row != hoveredRow) {
                    hoveredRow = row;
                    table.repaint();
                }
            }
        });

        table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                if (hoveredRow != -1) {
                    hoveredRow = -1;
                    table.repaint();
                }
            }
        });
    }
}
