/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.ensarium.dispense;

import com.aldrin.ensarium.db.Db;
import com.aldrin.ensarium.icons.FaSwingIcons;
import com.aldrin.ensarium.ui.widgets.BootstrapTableStyle;
import com.aldrin.ensarium.ui.widgets.RoundedScrollPane;
import de.jensd.fx.glyphs.fontawesome.FontAwesomeIcon;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Dimension;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author ALDRIN CABUSOG
 */
public class SearchProductDialog2 extends javax.swing.JDialog {

    private final ProductDao dao = new ProductDao();
//    private final JTextField txtSearch = new JTextField();
//    private final JSpinner 
    private final SearchProductDialog2.ProductTableModel model = new SearchProductDialog2.ProductTableModel();
//    private final JTable table = new JTable(model);
    private SearchProductDialog2.Result result;

    Icon iconSearch = FaSwingIcons.icon(FontAwesomeIcon.SEARCH, 24, Color.WHITE);
    Icon iconSelect = FaSwingIcons.icon(FontAwesomeIcon.MOUSE_POINTER, 24, Color.WHITE);
    Icon iconCancel = FaSwingIcons.icon(FontAwesomeIcon.CLOSE, 24, Color.WHITE);

    /**
     * Creates new form SearchProductDialog2
     */
//    public SearchProductDialog2(java.awt.Frame parent, boolean modal) {
    public SearchProductDialog2(java.awt.Window owner, String initialQuery) {
        super(owner, "Search Product", Dialog.ModalityType.APPLICATION_MODAL);
//        super(parent, modal);
        initComponents();
        

        txtSearch.putClientProperty("JTextField.placeholderText", "Search product");

        jSpinner1 = new JSpinner(new SpinnerNumberModel(1.0, 0.01, 999999.0, 1.0));

        btnCancel.setDanger();
        btnCancel.setIcon(iconCancel);

        btnFind.setPrimary();
        btnFind.setIcon(iconSearch);

        btnSelect.setPrimary();
        btnSelect.setIcon(iconSelect);

        tablePanel.add(new RoundedScrollPane(table), BorderLayout.CENTER);

        txtSearch.setText(initialQuery == null ? "" : initialQuery);
        btnFind.addActionListener(e -> search());
        txtSearch.addActionListener(e -> search());
        btnSelect.addActionListener(e -> choose());
        btnCancel.addActionListener(e -> dispose());
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {
                    choose();
                }
            }
        });

        table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);




//        hideColumn(0);
//        hideColumn(1);
//
        table.getColumnModel().getColumn(0).setPreferredWidth(100);
        table.getColumnModel().getColumn(1).setPreferredWidth(100);
        table.getColumnModel().getColumn(2).setPreferredWidth(350);
        table.getColumnModel().getColumn(3).setPreferredWidth(80);
        table.getColumnModel().getColumn(4).setPreferredWidth(80);
        table.getColumnModel().getColumn(5).setPreferredWidth(80);
        

        BootstrapTableStyle.setColumnLeft(table, 0);
        BootstrapTableStyle.setColumnLeft(table, 1);
        BootstrapTableStyle.setColumnLeft(table, 2);
        BootstrapTableStyle.setColumnLeft(table, 3);
        BootstrapTableStyle.setColumnRight(table, 4);
        BootstrapTableStyle.setColumnRight(table, 5);

        BootstrapTableStyle.setHeaderLeft(table, 0);
        BootstrapTableStyle.setHeaderLeft(table, 1);
        BootstrapTableStyle.setHeaderLeft(table, 2);
        BootstrapTableStyle.setHeaderLeft(table, 3);
        BootstrapTableStyle.setHeaderRight(table, 4);
        BootstrapTableStyle.setHeaderRight(table, 5);
        
        BootstrapTableStyle.installAll(this);
        
        installTableHover();

        search();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tablePanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnFind = new com.aldrin.ensarium.ui.widgets.StyledButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner(new SpinnerNumberModel(1.0, 0.01, 999999.0, 1.0));
        jPanel8 = new javax.swing.JPanel();
        btnSelect = new com.aldrin.ensarium.ui.widgets.StyledButton();
        btnCancel = new com.aldrin.ensarium.ui.widgets.StyledButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        tablePanel.setLayout(new java.awt.BorderLayout());
        jPanel1.add(tablePanel, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(882, 45));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel2.setText("Search");
        jPanel3.add(jLabel2);

        txtSearch.setMargin(new java.awt.Insets(2, 2, 2, 2));
        txtSearch.setMinimumSize(new java.awt.Dimension(600, 22));
        txtSearch.setPreferredSize(new java.awt.Dimension(825, 27));
        jPanel3.add(txtSearch);

        btnFind.setText("Find");
        jPanel3.add(btnFind);

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setPreferredSize(new java.awt.Dimension(882, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        jLabel1.setText("Qty");
        jPanel7.add(jLabel1);

        jSpinner1.setMinimumSize(new java.awt.Dimension(64, 27));
        jSpinner1.setPreferredSize(new java.awt.Dimension(64, 27));
        jPanel7.add(jSpinner1);

        jPanel4.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel8.setPreferredSize(new java.awt.Dimension(205, 50));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        btnSelect.setText("Select");
        btnSelect.addActionListener(this::btnSelectActionPerformed);
        jPanel8.add(btnSelect);

        btnCancel.setText("Close");
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        jPanel8.add(btnCancel);

        jPanel4.add(jPanel8, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jPanel5.setPreferredSize(new java.awt.Dimension(10, 280));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.EAST);

        jPanel6.setPreferredSize(new java.awt.Dimension(10, 280));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(999, 522));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.aldrin.ensarium.ui.widgets.StyledButton btnCancel;
    private com.aldrin.ensarium.ui.widgets.StyledButton btnFind;
    private com.aldrin.ensarium.ui.widgets.StyledButton btnSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void search() {
        try (var conn = Db.getConnection()) {
            conn.setAutoCommit(false);
            List<ProductOption> rows = dao.search(conn, txtSearch.getText().trim());
            conn.commit();
            model.setRows(rows);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void choose() {
        int row = table.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Select a product.");
            return;
        }
        ProductOption p = model.get(row);
        BigDecimal qty = BigDecimal.valueOf(((Number) jSpinner1.getValue()).doubleValue());
        if (qty.compareTo(p.onHandQty) > 0) {
            JOptionPane.showMessageDialog(this,
                    "Only " + p.onHandQty.stripTrailingZeros().toPlainString() + " remaining for " + p.productName + ".",
                    "Insufficient Stock", JOptionPane.WARNING_MESSAGE);
            return;
        }
        result = new Result();
        result.product = p;
        result.qty = qty;
        dispose();
    }

    public Result showDialog() {
        setVisible(true);
        return result;
    }

    public static class Result {

        public ProductOption product;
        public BigDecimal qty;
    }

    private static class ProductTableModel extends AbstractTableModel {

        private final String[] cols = {"Barcode", "SKU", "Product", "UOM", "On Hand", "Price"};
        private List<ProductOption> rows = new ArrayList<>();

        public void setRows(List<ProductOption> rows) {
            this.rows = rows;
            fireTableDataChanged();
        }

        public ProductOption get(int i) {
            return rows.get(i);
        }

        @Override
        public int getRowCount() {
            return rows.size();
        }

        @Override
        public int getColumnCount() {
            return cols.length;
        }

        @Override
        public String getColumnName(int c) {
            return cols[c];
        }

        @Override
        public Object getValueAt(int r, int c) {
            ProductOption p = rows.get(r);
            return switch (c) {
                case 0 ->
                    p.barcode;
                case 1 ->
                    p.sku;
                case 2 ->
                    p.productName;
                case 3 ->
                    p.uomCode;
                case 4 ->
                    p.onHandQty.setScale(2, RoundingMode.HALF_UP);
                default ->
                    p.unitPrice.setScale(2, RoundingMode.HALF_UP);
            };
        }
    }

    
    private final JTable table = new JTable(model) {
        @Override
        public Component prepareRenderer(TableCellRenderer renderer, int row, int column) {
            Component c = super.prepareRenderer(renderer, row, column);

            if (!isRowSelected(row)) {
                if (row == hoveredRow) {
                    c.setBackground(new Color(0xE8F2FF)); // hover color
                } else {
                    c.setBackground((row % 2 == 0) ? Color.WHITE : new Color(0xF7F9FC)); // stripes
                }
                c.setForeground(Color.BLACK);
            } else {
                c.setBackground(getSelectionBackground());
                c.setForeground(getSelectionForeground());
            }

            if (c instanceof JComponent jc) {
                jc.setOpaque(true);
            }

            return c;
        }
    };
    
    private int hoveredRow = -1;

    private void installTableHover() {
        table.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseMoved(java.awt.event.MouseEvent e) {
                int row = table.rowAtPoint(e.getPoint());
                if (row != hoveredRow) {
                    hoveredRow = row;
                    table.repaint();
                }
            }
        });

        table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                if (hoveredRow != -1) {
                    hoveredRow = -1;
                    table.repaint();
                }
            }
        });
    }

}
