/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.aldrin.ensarium.ui;

import com.aldrin.ensarium.icons.FaSwingIcons;
import com.aldrin.ensarium.security.Session;
import com.aldrin.ensarium.service.UserService;
import com.aldrin.ensarium.util.RememberMeStore;
import com.aldrin.ensarium.util.SwingUtils;
import de.jensd.fx.glyphs.fontawesome.FontAwesomeIcon;
import java.awt.Color;
import javax.swing.Icon;

/**
 *
 * @author ALDRIN CABUSOG
 */
public class ChangePasswordDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChangePasswordDialog.class.getName());
    private final UserService userService = new UserService();

    /**
     * Creates new form ChangePasswordDialog
     */
    private Session session;
    Icon iconCheck = FaSwingIcons.icon(FontAwesomeIcon.CHECK, 18, Color.WHITE);
    Icon iconCancel = FaSwingIcons.icon(FontAwesomeIcon.CLOSE, 18, Color.WHITE);

    public ChangePasswordDialog(java.awt.Frame parent, Session session, boolean modal) {
//    public ChangePasswordDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.session = session;
        initComponents();
        txtOldPassword.putClientProperty("JTextField.placeholderText", "Enter old password");
        txtNewPassword.putClientProperty("JTextField.placeholderText", "Enter new password");
        btnCancel.setDanger();
        btnOk.setIcon(iconCheck);
        btnCancel.setIcon(iconCancel);
        getRootPane().setDefaultButton(btnOk);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtOldPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnOk = new com.aldrin.ensarium.ui.widgets.StyledButton();
        btnCancel = new com.aldrin.ensarium.ui.widgets.StyledButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change password");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
        jPanel7.add(txtOldPassword);
        jPanel7.add(txtNewPassword);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel8.setPreferredSize(new java.awt.Dimension(100, 95));
        jPanel8.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setText("Old password");
        jPanel8.add(jLabel1);

        jLabel2.setText("New password");
        jPanel8.add(jLabel2);

        jPanel3.add(jPanel8, java.awt.BorderLayout.WEST);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setPreferredSize(new java.awt.Dimension(445, 10));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel5.setPreferredSize(new java.awt.Dimension(445, 50));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        btnOk.setText("Ok");
        btnOk.setPreferredSize(new java.awt.Dimension(90, 27));
        btnOk.addActionListener(this::btnOkActionPerformed);
        jPanel5.add(btnOk);

        btnCancel.setText("Cancel");
        btnCancel.setPreferredSize(new java.awt.Dimension(90, 27));
        jPanel5.add(btnCancel);

        jPanel1.add(jPanel5, java.awt.BorderLayout.SOUTH);

        jPanel6.setPreferredSize(new java.awt.Dimension(10, 106));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.LINE_END);

        jPanel9.setPreferredSize(new java.awt.Dimension(10, 106));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, java.awt.BorderLayout.LINE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(416, 159));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
//        try {
//            boolean ok = userService.verifyAndChangePassword(session.userId(), new String(txtOldPassword.getPassword()), new String(txtNewPassword.getPassword()));
//            if (!ok) {
//                SwingUtils.info(this, "Old password is incorrect.");
//                return;
//            } else {
//                dispose();
//            }
//            SwingUtils.info(this, "Password changed successfully.");
//        } catch (Exception ex) {
//            SwingUtils.error(this, "Failed to change password.", (Exception) ex);
//        }

        try {
            boolean ok = userService.verifyAndChangePassword(
                    session.userId(),
                    new String(txtOldPassword.getPassword()),
                    new String(txtNewPassword.getPassword())
            );

            if (!ok) {
                SwingUtils.info(this, "Old password is incorrect.");
                return;
            }

            RememberMeStore.clear();
            SwingUtils.info(this, "Password changed successfully. Please log in again.");
            dispose();
        } catch (Exception ex) {
            SwingUtils.error(this, "Failed to change password.", (Exception) ex);
        }
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.aldrin.ensarium.ui.widgets.StyledButton btnCancel;
    public com.aldrin.ensarium.ui.widgets.StyledButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JPasswordField txtNewPassword;
    public javax.swing.JPasswordField txtOldPassword;
    // End of variables declaration//GEN-END:variables
}
